SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

TARGET_FPS: float = 60

LINE_WIDTH: int = 2

PLAYER_RADIUS: float = 20
PLAYER_TURN_SPEED: float = 300
PLAYER_SPEED: float = 200
PLAYER_SHOOT_SPEED: float = 500
BULLET_RADIUS: float = 5
MAX_BULLETS: int = 3
BULLET_LIFESPAN: float = 1.5

ASTEROID_SIZES: int = 3
ASTEROID_MIN_RADIUS: float = 20
ASTEROID_SPAWN_RATE_SECONDS: float = 0.8
ASTEROID_MAX_RADIUS: float = ASTEROID_MIN_RADIUS * ASTEROID_SIZES
ASTEROID_SPEED_SCALE_FACTOR: float = 1.2

VECTOR_FONT_POINT_WIDTH: float = 3.0
